[package]
name = "shuodedaoli"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.2"
egui = "0.26.2"
egui_extras = { version = "0.26.2", features = ["image"] }
image = "0.24.9"
nalgebra = "0.32.4"
ndarray = "0.15.6"
rayon = "1.9.0"
rfd = "0.14.0"
